[package]
name = "deported"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.31.1", features = ["process", "signal"] }
# process-man = { version = "0.1.0", path = "process-man" }
tokio = { version = "1.49.0", features = ["process", "rt", "macros", "io-util", "sync", "net", "time", "signal"] }
tracing = "0.1.44"
